version: 2
jobs:
  build:
    branches:
      ignore: gh-pages

    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run lint

      - run: npm test

      - run: npm run build:pages

      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == master ]; then
              git config --global user.email "circleci@users.noreply.github.com"
              git config --global user.name "CircleCI"
              git clone $CIRCLE_REPOSITORY_URL deploy

              cd deploy
              git checkout gh-pages || git checkout --orphan gh-pages
              git rm -rf .
              cd ..

              npm run export

              cp -a out/. deploy/.

              mkdir -p deploy/.circleci && cp -a .circleci/. deploy/.circleci/.
              cd deploy

              touch .nojekyll
              git add -A
              git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

              git push origin gh-pages
            fi
